# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 513)
        MainWindow.setStyleSheet("background-color : rgb(201, 255, 224);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.updateprofile = QtWidgets.QPushButton(self.centralwidget)
        self.updateprofile.setGeometry(QtCore.QRect(160, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.updateprofile.setFont(font)
        self.updateprofile.setStyleSheet("border-radius :30px;\n"
"background-color:rgb(135, 135, 135);\n"
"color : rgb(255, 255, 255)")
        self.updateprofile.setObjectName("updateprofile")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(160, 290, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("border-radius :30px;\n"
"background-color:rgb(135, 135, 135);\n"
"color : rgb(255, 255, 255)")
        self.logout.setObjectName("logout")
        self.changepassword = QtWidgets.QPushButton(self.centralwidget)
        self.changepassword.setGeometry(QtCore.QRect(160, 170, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.changepassword.setFont(font)
        self.changepassword.setStyleSheet("border-radius :30px;\n"
"background-color:rgb(135, 135, 135);\n"
"color : rgb(255, 255, 255)")
        self.changepassword.setObjectName("changepassword")
        self.logout_2 = QtWidgets.QPushButton(self.centralwidget)
        self.logout_2.setGeometry(QtCore.QRect(160, 400, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.logout_2.setFont(font)
        self.logout_2.setStyleSheet("border-radius :30px;\n"
"background-color:rgb(135, 135, 135);\n"
"color : rgb(255, 255, 255)")
        self.logout_2.setObjectName("logout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.updateprofile.setText(_translate("MainWindow", "Update profile"))
        self.logout.setText(_translate("MainWindow", "Log out"))
        self.changepassword.setText(_translate("MainWindow", "Change Password"))
        self.logout_2.setText(_translate("MainWindow", "Back"))
import MENU_rc
