# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fillprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bgwidget = QtWidgets.QWidget(self.centralwidget)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.bgwidget.setStyleSheet("background-color: url(:/MENU/Healthy.jpg);")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 351, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.signup = QtWidgets.QPushButton(self.bgwidget)
        self.signup.setGeometry(QtCore.QRect(170, 500, 271, 51))
        self.signup.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(208, 245, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.signup.setObjectName("signup")
        self.username = QtWidgets.QLineEdit(self.bgwidget)
        self.username.setGeometry(QtCore.QRect(170, 170, 341, 51))
        self.username.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px ;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.username.setObjectName("username")
        self.Height_2 = QtWidgets.QLineEdit(self.bgwidget)
        self.Height_2.setGeometry(QtCore.QRect(170, 330, 341, 51))
        self.Height_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px ;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Height_2.setObjectName("Height_2")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(440, 456, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.Height = QtWidgets.QLabel(self.bgwidget)
        self.Height.setGeometry(QtCore.QRect(70, 330, 81, 20))
        self.Height.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.Height.setObjectName("Height")
        self.Weight = QtWidgets.QLineEdit(self.bgwidget)
        self.Weight.setGeometry(QtCore.QRect(170, 410, 341, 51))
        self.Weight.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px ;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Weight.setObjectName("Weight")
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 250, 81, 20))
        self.label_9.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.bgwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 410, 81, 20))
        self.label_10.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.signup_2 = QtWidgets.QPushButton(self.bgwidget)
        self.signup_2.setGeometry(QtCore.QRect(170, 570, 271, 41))
        self.signup_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(208, 245, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.signup_2.setObjectName("signup_2")
        self.Age = QtWidgets.QLineEdit(self.bgwidget)
        self.Age.setGeometry(QtCore.QRect(170, 250, 341, 51))
        self.Age.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px ;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Age.setObjectName("Age")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -110, 1201, 801))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setStyleSheet("background-image : url(:/MENU/Healthy.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.signup.raise_()
        self.username.raise_()
        self.Height_2.raise_()
        self.label_4.raise_()
        self.error.raise_()
        self.Height.raise_()
        self.Weight.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.signup_2.raise_()
        self.Age.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Fill  your profile"))
        self.signup.setText(_translate("MainWindow", "Save"))
        self.label_4.setText(_translate("MainWindow", "First Name"))
        self.Height.setText(_translate("MainWindow", "Height"))
        self.label_9.setText(_translate("MainWindow", "Age"))
        self.label_10.setText(_translate("MainWindow", "Weight (Kg)"))
        self.signup_2.setText(_translate("MainWindow", "BACK"))
import MENU_rc
