# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gym.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 617)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 10, 151, 81))
        self.label.setStyleSheet("border-color: rgb(255, 170, 0);\n"
"font: 75 48pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"font:50pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.view = QtWidgets.QLabel(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(219, 100, 600, 450))
        self.view.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.view.setText("")
        self.view.setObjectName("view")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 490, 171, 51))
        self.back.setStyleSheet("background-color: rgb(135, 135, 135);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.back.setObjectName("back")
        self.information = QtWidgets.QLabel(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(910, 310, 261, 241))
        self.information.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.information.setText("")
        self.information.setPixmap(QtGui.QPixmap(":/MENU/gym_gif.gif"))
        self.information.setObjectName("information")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1040, 150, 111, 91))
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 140, 121, 61))
        self.label_2.setStyleSheet("border-color: rgb(255, 170, 0);\n"
"font: 45 48pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"font:30pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.SeeVideo = QtWidgets.QPushButton(self.centralwidget)
        self.SeeVideo.setGeometry(QtCore.QRect(1100, 560, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.SeeVideo.setFont(font)
        self.SeeVideo.setStyleSheet("background-color: rgb(135, 135, 135);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.SeeVideo.setObjectName("SeeVideo")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 60, 121, 51))
        self.label_4.setStyleSheet("border-color: rgb(255, 170, 0);\n"
"font: 45 48pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"font:30pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(1040, 40, 111, 91))
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(20, 420, 171, 51))
        self.Start.setStyleSheet("background-color: rgb(135, 135, 135);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.Start.setObjectName("Start")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.mute_2 = QtWidgets.QPushButton(self.centralwidget)
        self.mute_2.setGeometry(QtCore.QRect(50, 20, 51, 41))
        self.mute_2.setStyleSheet("border-image : url(:/MENU/unmute.png);")
        self.mute_2.setText("")
        self.mute_2.setObjectName("mute_2")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(900, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color : rgb(255, 255, 255);")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.mute_2.raise_()
        self.label.raise_()
        self.view.raise_()
        self.back.raise_()
        self.information.raise_()
        self.lcdNumber.raise_()
        self.label_2.raise_()
        self.SeeVideo.raise_()
        self.label_4.raise_()
        self.lcdNumber_2.raise_()
        self.Start.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.timeLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GYM"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.label_2.setText(_translate("MainWindow", " REP"))
        self.SeeVideo.setText(_translate("MainWindow", "See video"))
        self.label_4.setText(_translate("MainWindow", "Round"))
        self.Start.setText(_translate("MainWindow", "START"))
        self.label_3.setText(_translate("MainWindow", "Option"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Barbell Cruls Left"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Push Up"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Barbell Cruls Right"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Dumbbell flyes"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Dumbbell_shoulder"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Swat"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Skull Crusher Left"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Skull Crusher Right"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Crunch"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Leg raise"))
        self.timeLabel.setText(_translate("MainWindow", "00:00"))
import MENU_rc
