# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 736)
        MainWindow.setStyleSheet("border-image:url(:/MENU/Photo-Background-Application.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(430, 40, 191, 111))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Calibri\";\n"
"color: rgb(0, 0, 0);\n"
"font:50pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.TimeTable = QtWidgets.QPushButton(self.centralwidget)
        self.TimeTable.setGeometry(QtCore.QRect(230, 230, 131, 121))
        self.TimeTable.setStyleSheet("border-image: url(:/MENU/R (2).png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.TimeTable.setText("")
        self.TimeTable.setObjectName("TimeTable")
        self.Gym = QtWidgets.QPushButton(self.centralwidget)
        self.Gym.setGeometry(QtCore.QRect(440, 200, 191, 151))
        self.Gym.setStyleSheet("border-image:url(:/MENU/crossfit-icon-3.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.Gym.setText("")
        self.Gym.setObjectName("Gym")
        self.Yoga = QtWidgets.QPushButton(self.centralwidget)
        self.Yoga.setGeometry(QtCore.QRect(690, 220, 141, 131))
        self.Yoga.setStyleSheet("border-image:url(:/MENU/img_36137.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.Yoga.setText("")
        self.Yoga.setObjectName("Yoga")
        self.Profile = QtWidgets.QPushButton(self.centralwidget)
        self.Profile.setGeometry(QtCore.QRect(480, 440, 111, 101))
        self.Profile.setStyleSheet("border-image:url(:/MENU/R (1).png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.Profile.setText("")
        self.Profile.setObjectName("Profile")
        self.Chat = QtWidgets.QPushButton(self.centralwidget)
        self.Chat.setGeometry(QtCore.QRect(700, 430, 121, 111))
        self.Chat.setStyleSheet("border-image:url(:/MENU/R.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.Chat.setText("")
        self.Chat.setObjectName("Chat")
        self.Profile_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Profile_2.setGeometry(QtCore.QRect(250, 440, 101, 101))
        self.Profile_2.setStyleSheet("border-image:url(:/MENU/db.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.Profile_2.setText("")
        self.Profile_2.setObjectName("Profile_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 380, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 380, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(710, 380, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(700, 570, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 570, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 570, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MENU"))
        self.label_2.setText(_translate("MainWindow", "Time table"))
        self.label_3.setText(_translate("MainWindow", "Time table"))
        self.label_4.setText(_translate("MainWindow", "Time table"))
        self.label_5.setText(_translate("MainWindow", "Support"))
        self.label_6.setText(_translate("MainWindow", "Profile"))
        self.label_7.setText(_translate("MainWindow", "History"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
