# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtWidgets import *


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        # MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(70, 330, 211, 41))
        self.login.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"QPushButton::hover\n"
"                             {\n"
"                            background-color : lightgreen;\n"
"                             }")
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 800, 450))
        self.label_2.setStyleSheet("background-image:url(:/MENU/60513-01-gym-powerpoint-template-light-16x9-1.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.emailfield = QtWidgets.QLineEdit(self.centralwidget)
        self.emailfield.setGeometry(QtCore.QRect(30, 140, 321, 41))
        self.emailfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.emailfield.setObjectName("emailfield")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 151, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 81, 20))
        self.label_4.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.passwordfield = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordfield.setGeometry(QtCore.QRect(30, 240, 321, 41))
        self.passwordfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.passwordfield.setObjectName("passwordfield")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(810, 576, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_2.raise_()
        self.login.raise_()
        self.label_3.raise_()
        self.emailfield.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.passwordfield.raise_()
        self.error.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.login.setText(_translate("MainWindow", "Log in"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Password"))
import MENU_rc
